# Generated by Django 3.1.7 on 2021-03-23 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.CharField(default=uuid.UUID('8313c4c5-0f51-457b-af24-3cba5108b981'), max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=4000)),
                ('rounds', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('money_at_start', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.CharField(default=uuid.UUID('96765133-b031-4802-962b-93a470861c56'), max_length=256, primary_key=True, serialize=False)),
                ('roundNumber', models.PositiveSmallIntegerField()),
                ('roundName', models.CharField(max_length=256)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=uuid.UUID('3c29d3bb-e616-46d4-99d4-62ad7e2a559b'), max_length=256, primary_key=True, serialize=False)),
                ('teamCode', models.CharField(max_length=256)),
                ('createdBy', models.CharField(max_length=256)),
                ('teamName', models.CharField(max_length=256, unique=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=uuid.UUID('57a28adb-531a-41f3-94a8-6011b59a51ba'), max_length=256, primary_key=True, serialize=False)),
                ('fileUrl', models.URLField(max_length=256)),
                ('languageUsed', models.CharField(max_length=256)),
                ('timeOfSubmission', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('checkedOrNot', models.BooleanField(default=False)),
                ('checkedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('roundId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.round')),
                ('teamCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.team')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=uuid.UUID('b342a999-de4e-47ee-97c6-b1594714f4a7'), max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('input', models.TextField(blank=True, max_length=256, null=True)),
                ('output', models.TextField(blank=True, max_length=256, null=True)),
                ('test_input', models.TextField(blank=True, max_length=256, null=True)),
                ('test_output', models.TextField(blank=True, max_length=256, null=True)),
                ('points', models.PositiveBigIntegerField(blank=True, default=2500, null=True)),
                ('roundId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.round')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.CharField(default=uuid.UUID('a5325833-225a-4e9e-a79e-6766ec6d790b'), max_length=256, primary_key=True, serialize=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.contest')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.team')),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.CharField(default=uuid.UUID('c7ec00c7-5d65-499e-8075-eb3bcd38cd84'), max_length=256, primary_key=True, serialize=False)),
                ('componentName', models.CharField(max_length=256)),
                ('componentDescription', models.TextField(max_length=256)),
                ('componentPrice', models.PositiveBigIntegerField(default=100)),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.contest')),
            ],
        ),
    ]
