# Generated by Django 3.1.7 on 2021-03-23 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.CharField(default=uuid.UUID('95a2218c-5474-4b9c-b04d-c889a5cca344'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(default=uuid.UUID('dfb990b7-22ea-4670-9c2a-af02ffaad97e'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='id',
            field=models.CharField(default=uuid.UUID('931aec6a-93b2-4971-8a6a-8abce30d043f'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.UUID('77e0877d-879c-4469-9202-0973baeb9dfa'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default=uuid.UUID('a7cc793b-675d-4fec-a597-8e57a5461387'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.UUID('c6b10a54-1912-45c2-ae84-26b388bf0db5'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(default=uuid.UUID('246b02bd-8e29-4d6b-ac98-d9c9fa4ea194'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
