# Generated by Django 3.1.7 on 2021-03-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0002_auto_20210323_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.CharField(default=uuid.UUID('729a7260-b355-4fac-b4cb-98d66c0e8c7e'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(default=uuid.UUID('c318beb9-3275-4126-a1a1-47c2069bdf74'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='id',
            field=models.CharField(default=uuid.UUID('90663d8e-ec39-4cbf-b077-bdfae6112bf0'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.UUID('bc6da814-fb56-40ed-b418-febe50789364'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default=uuid.UUID('88330dae-d491-4d4e-8561-5e1c502e7534'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.UUID('9fa291c6-33e6-43f5-8c7f-be1723d99d25'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(default=uuid.UUID('373d3389-ac66-404d-8173-b7707583b157'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
