# Generated by Django 3.1.4 on 2020-12-27 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.CharField(default=uuid.UUID('952ad01f-9f18-4589-8861-1ac5ab711df1'), max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('rounds', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('money_at_start', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=uuid.UUID('b76a45eb-389e-4cc7-8ea9-2be904d00498'), max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=5000)),
                ('input', models.TextField(max_length=256)),
                ('output', models.TextField(max_length=256)),
                ('test_input', models.TextField(blank=True, max_length=256, null=True)),
                ('test_output', models.TextField(blank=True, max_length=256, null=True)),
                ('points', models.PositiveBigIntegerField(default=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=uuid.UUID('d4d266db-767b-4036-b2f9-c4cc99416af3'), max_length=256, primary_key=True, serialize=False)),
                ('fileUrl', models.URLField(max_length=256)),
                ('languageUsed', models.CharField(max_length=256)),
                ('timeOfSubmission', models.DateTimeField(auto_now_add=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.question')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.CharField(default=uuid.UUID('58d8b051-f249-4180-89aa-81acb4f5a49c'), max_length=256, primary_key=True, serialize=False)),
                ('roundNumber', models.PositiveSmallIntegerField()),
                ('roundName', models.CharField(max_length=256)),
                ('startTime', models.DateTimeField()),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.contest')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='roundId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.round'),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.CharField(default=uuid.UUID('5ff8e23c-9dc1-4638-8903-57acc656b6b0'), max_length=256, primary_key=True, serialize=False)),
                ('componentName', models.CharField(max_length=256)),
                ('componentDescription', models.TextField(max_length=256)),
                ('componentPrice', models.PositiveBigIntegerField(default=100)),
                ('contestId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.contest')),
            ],
        ),
    ]
