# Generated by Django 3.1.4 on 2020-12-27 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.CharField(default=uuid.UUID('f82e19df-7b5e-4037-9a23-a9263e9494f5'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(default=uuid.UUID('61ccf11c-0188-4f6a-a31c-d0d1342f1d31'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.UUID('84b2c1af-88c2-4d5f-864d-3fcdc8e9d8bf'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default=uuid.UUID('a02fb92f-9a07-4c1e-8fd8-9ed0b4aa78a4'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.UUID('00cb38e5-70c1-43e7-9a19-8cba04826de2'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
