# Generated by Django 3.1.4 on 2020-12-27 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20201227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.CharField(default=uuid.UUID('712ae010-854c-4f53-b086-a904ef5a15d4'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(default=uuid.UUID('fad2d0a2-22dc-4313-8ba6-1d8bb7174f67'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.UUID('2d0b1589-0dac-40d2-8cc7-513502f7f268'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default=uuid.UUID('ed97047c-93cc-49db-9602-1b2ea8d9cdd2'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.UUID('a210105a-9933-4b9f-8d21-22e2dc7d6ad9'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
