# Generated by Django 3.1.4 on 2020-12-28 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20201227_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='contestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.contest'),
        ),
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.CharField(default=uuid.UUID('1d0c02d2-529b-4ec9-bfdd-7fcc8515d1ed'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.CharField(default=uuid.UUID('e8a6785e-0440-4fe8-98b9-433b0116df6e'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=uuid.UUID('36a7810a-2750-459b-9cc2-232b642945a1'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='roundId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='contestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.contest'),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default=uuid.UUID('b8113d46-62f9-478b-b85c-03aa94320600'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(default=uuid.UUID('a33db36f-e527-409a-8083-4c93ae2afbfc'), max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.question'),
        ),
    ]
