# Generated by Django 3.1.4 on 2021-02-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210103_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
